export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOTPOST: '/hotpost',
  HOTPOST_CLUE: (clueId: string) => `/hotpost/clues/${clueId}`,
  HOTPOST_BOX: '/hotpost/box',
  HOTPOST_LAB_SEARCH: '/hotpost/lab/search',
  HOTPOST_RESULT: (queryId: string) => `/hotpost/result/${queryId}`,
  PROGRESS: (taskId: string) => `/progress/${taskId}`,
  REPORT: (taskId: string) => `/report/${taskId}`,
  STANDARD_REPORT: (slug: string) => `/standard-report/${slug}`,
  INSIGHTS: '/insights',
  DECISION_UNITS: '/decision-units',
  DASHBOARD: '/dashboard',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_CANDIDATES: '/admin/communities/discovered',
  ADMIN_POOL: '/admin/communities/pool',
  ADMIN_COMMUNITY_IMPORT: '/admin/communities/import',
  ADMIN_TASK_LEDGER: '/admin/tasks/ledger',
  INSIGHTS_TASK: (taskId: string) => `/insights/${taskId}`,
};
