from __future__ import annotations

"""
Import a curated CSV lexicon (theme,type,term) and produce YAML semantic set.

Optionally auto-fill missing pain_points per theme using suggestion CSVs
generated by `make semantic-suggest`.

Usage:
  python backend/scripts/semantic_lexicon_import.py \
    --input backend/reports/local-acceptance/semantic-lexicon-v1.csv \
    --output backend/config/semantic_sets/crossborder.yml \
    --suggest-pain backend/reports/local-acceptance/semantic-suggested-pain_points.csv \
    --suggest-alias backend/reports/local-acceptance/semantic-suggested-aliases.csv \
    --pain-top 30
"""

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set

import yaml


DEFAULT_EXCLUDES = ["meme", "funny", "gaming", "movie", "anime", "gif", "porn"]

# Conservative trigger patterns to qualify a phrase as a pain point
TRIGGER_PATTERNS = [
    r"\bban(ned|ning)?\b",
    r"\bsuspend(ed|sion)?\b",
    r"\bpolicy\b",
    r"\bviolation(s)?\b",
    r"\brefund(s|ed)?\b",
    r"\breturn(s|ed)?\b",
    r"\bchargeback(s)?\b",
    r"\bscam(my)?\b",
    r"\bfraud(ulent)?\b",
    r"\bgated\b|\bungated\b",
    r"\binfring(e|ement)\b",
    r"\bcopyright\b",
    r"\btrademark\b",
    r"\bstrike(s)?\b",
    r"\bvat\b",
    r"\btax(es)?\b",
    r"\bcustoms?\b",
    r"\bdut(y|ies)\b",
    r"\b(seiz(e|ed|ure)|hold)\b",
    r"\bdelay(ed)?\b",
    r"lost package",
    r"封号|冻结|违规|申诉|侵权|合规|关税|扣留|清关|延迟|丢件|退货|退款",
]

TRIGGER_REGEX = re.compile("|".join(TRIGGER_PATTERNS), re.IGNORECASE)


def is_pain_phrase(phrase: str) -> bool:
    s = (phrase or "").strip()
    if len(s) < 3:
        return False
    # Drop likely false-positives seen in quick runs
    BLACKLIST = {"holder", "calculate", "motivated"}
    if s.lower() in BLACKLIST:
        return False
    return TRIGGER_REGEX.search(s) is not None


def read_curated(input_csv: Path) -> Dict[str, Dict[str, List[str]]]:
    buckets: Dict[str, Dict[str, List[str]]] = defaultdict(lambda: {"brands": [], "features": [], "pain_points": [], "exclude": []})
    with input_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            theme = str(row.get("theme", "")).strip()
            typ = str(row.get("type", "")).strip()
            term = str(row.get("term", "")).strip()
            if not theme or not typ or not term:
                continue
            key = typ.lower()
            if key not in {"brands", "features", "pain_points", "exclude"}:
                continue
            arr = buckets[theme][key]
            if term not in arr:
                arr.append(term)
    return buckets


def read_suggested_pain(suggest_csv: Path, top_n: int = 30) -> Dict[str, List[str]]:
    if not suggest_csv.exists():
        return {}
    grouped: Dict[str, List[tuple[str, int]]] = defaultdict(list)
    with suggest_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            theme = str(row.get("theme", "")).strip()
            phrase = str(row.get("phrase", "")).strip()
            try:
                cnt = int(str(row.get("count", "0") or "0"))
            except Exception:
                cnt = 0
            if not theme or not phrase:
                continue
            if not is_pain_phrase(phrase):
                continue
            grouped[theme].append((phrase, cnt))
    out: Dict[str, List[str]] = {}
    for theme, arr in grouped.items():
        arr.sort(key=lambda x: x[1], reverse=True)
        uniq: List[str] = []
        seen: Set[str] = set()
        for phrase, _ in arr:
            low = phrase.lower()
            if low in seen:
                continue
            seen.add(low)
            uniq.append(phrase)
            if len(uniq) >= top_n:
                break
        if uniq:
            out[theme] = uniq
    return out


def read_suggested_aliases(alias_csv: Path) -> Dict[str, Dict[str, List[str]]]:
    if not alias_csv.exists():
        return {}
    out: Dict[str, Dict[str, List[str]]] = defaultdict(lambda: defaultdict(list))
    with alias_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            theme = str(row.get("theme", "")).strip()
            brand = str(row.get("brand", "")).strip()
            cand = str(row.get("candidate", "")).strip()
            if not theme or not brand or not cand:
                continue
            arr = out[theme][brand]
            if cand not in arr:
                arr.append(cand)
    return out


def write_yaml(buckets: Dict[str, Dict[str, List[str]]], aliases: Dict[str, Dict[str, List[str]]], output: Path) -> None:
    themes_section: Dict[str, Dict[str, object]] = {}
    for theme, parts in buckets.items():
        brands = sorted(list(dict.fromkeys(parts.get("brands", []))))
        features = sorted(list(dict.fromkeys(parts.get("features", []))))
        pain = sorted(list(dict.fromkeys(parts.get("pain_points", []))))
        exclude = sorted(list(dict.fromkeys((parts.get("exclude") or []) + DEFAULT_EXCLUDES)))
        alias_map = {b: sorted(list(dict.fromkeys(aliases.get(theme, {}).get(b, [])))) for b in brands}
        # remove empty alias lists
        alias_map = {k: v for k, v in alias_map.items() if v}
        themes_section[theme] = {
            "brands": brands,
            "features": features,
            "pain_points": pain,
            "aliases": alias_map,
            "exclude": exclude,
            "weights": {"brands": 1.5, "features": 1.0, "pain_points": 1.2},
        }

    payload = {"version": 1, "domain": "crossborder", "themes": themes_section}
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Import semantic lexicon CSV and produce YAML")
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--output", type=Path, default=Path("backend/config/semantic_sets/crossborder.yml"))
    ap.add_argument("--suggest-pain", type=Path, default=Path("backend/reports/local-acceptance/semantic-suggested-pain_points.csv"))
    ap.add_argument("--suggest-alias", type=Path, default=Path("backend/reports/local-acceptance/semantic-suggested-aliases.csv"))
    ap.add_argument("--pain-top", type=int, default=30)
    ap.add_argument("--fill-pain", action="store_true", help="If pain_points empty for a theme, fill from suggested")
    args = ap.parse_args()

    buckets = read_curated(args.input)

    # Optional auto-fill for pain points per theme
    if args.fill_pain:
        suggested = read_suggested_pain(args.suggest_pain, top_n=args.pain_top)
        for theme, parts in buckets.items():
            if not parts.get("pain_points"):
                parts["pain_points"] = suggested.get(theme, [])

    # Optional aliases
    alias_map = read_suggested_aliases(args.suggest_alias)

    write_yaml(buckets, alias_map, args.output)
    print(f"✅ Lexicon imported: {args.output}")


if __name__ == "__main__":
    main()

