"""
Pain point clustering utilities for Spec010 P0.

Combines lightweight TF-IDF embeddings with rule-based fallbacks to group the
raw pain point items generated by the analysis engine into 3-5 topical clusters.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
import re
from typing import Iterable, List, Mapping, Sequence

import numpy as np
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

_STOPWORDS = ENGLISH_STOP_WORDS.union(
    {
        "team",
        "teams",
        "seller",
        "sellers",
        "product",
        "products",
        "people",
        "users",
        "workflow",
        "process",
        "processes",
        "issue",
        "issues",
        "problem",
        "problems",
        "need",
        "needs",
        "help",
        "like",
        "just",
        "really",
        "also",
        "still",
        "make",
        "getting",
        "using",
        "trying",
        "does",
        "would",
        "could",
        "anyone",
        "something",
    }
)

_DEFAULT_THRESHOLDS: Sequence[float] = (0.35, 0.45, 0.55, 0.65)
_TOKEN_RE = re.compile(r"[a-zA-Z]{4,}")


@dataclass(slots=True)
class _PainPointRecord:
    description: str
    frequency: int
    sentiment: float
    communities: list[str]
    samples: list[str]
    document: str
    keywords: set[str]


def cluster_pain_points(
    pain_points: Sequence[Mapping[str, object]],
    *,
    min_clusters: int = 2,
    max_clusters: int = 5,
) -> list[dict[str, object]]:
    """
    Cluster pain point items into topical groups.

    Args:
        pain_points: Sequence of pain point dictionaries (as produced by the
            analysis engine / schemas.Analysis.PainPoint).
        min_clusters: Lower bound for clusters when there are enough items.
        max_clusters: Upper bound for clusters (capped by input size).

    Returns:
        A list of cluster summaries sorted by combined frequency (desc).
    """
    records = [_normalise_pain_point(item) for item in pain_points]
    records = [rec for rec in records if rec is not None]
    if not records:
        return []

    effective_min = max(1, min(min_clusters, len(records)))
    effective_max = max(effective_min, min(max_clusters, len(records)))

    if len(records) == 1:
        return [_summarise_cluster([0], records, None, None)]

    documents = [rec.document for rec in records]

    vectorizer: TfidfVectorizer | None = None
    matrix: np.ndarray | None = None
    try:
        vectorizer = TfidfVectorizer(
            stop_words=_STOPWORDS,
            ngram_range=(1, 2),
            max_features=80,
            norm="l2",
        )
        matrix = vectorizer.fit_transform(documents)
        if matrix.size == 0:
            matrix = None
    except ValueError:
        matrix = None

    clusters = _build_clusters(
        records, matrix, effective_min, effective_max
    )

    summaries = [
        _summarise_cluster(cluster, records, matrix, vectorizer)
        for cluster in clusters
    ]
    summaries.sort(key=lambda x: (-x["total_frequency"], x["negative_mean"]))

    for summary in summaries:
        summary.pop("total_frequency", None)

    return summaries


def _normalise_pain_point(item: Mapping[str, object]) -> _PainPointRecord | None:
    description = str(item.get("description") or "").strip()
    if not description:
        return None
    try:
        frequency = int(item.get("frequency") or 0)
    except (TypeError, ValueError):
        frequency = 0
    try:
        sentiment = float(item.get("sentiment_score") or 0.0)
    except (TypeError, ValueError):
        sentiment = 0.0

    example_posts = item.get("example_posts") or []
    communities: list[str] = []
    samples: list[str] = []
    if isinstance(example_posts, Iterable):
        for payload in example_posts:
            if not isinstance(payload, Mapping):
                continue
            community = str(payload.get("community") or "").strip()
            content = str(payload.get("content") or "").strip()
            if community:
                communities.append(community)
            if content:
                samples.append(content)

    user_examples = []
    raw_user_examples = item.get("user_examples") or []
    if isinstance(raw_user_examples, Iterable):
        for text in raw_user_examples:
            value = str(text or "").strip()
            if value:
                user_examples.append(value)

    if not samples:
        samples.append(description)

    document_parts = [description] + user_examples + samples
    document = " ".join(document_parts)

    return _PainPointRecord(
        description=description,
        frequency=frequency,
        sentiment=sentiment,
        communities=communities,
        samples=samples,
        document=document,
        keywords=_extract_keywords(description),
    )


def _extract_keywords(document: str) -> set[str]:
    tokens = set()
    for match in _TOKEN_RE.findall(document.lower()):
        token = match.strip()
        if len(token) < 5:
            continue
        if token in _STOPWORDS:
            continue
        tokens.add(token)
    return tokens


def _build_clusters(
    records: Sequence[_PainPointRecord],
    matrix: np.ndarray | None,
    min_clusters: int,
    max_clusters: int,
) -> list[list[int]]:
    count = len(records)
    keyword_pairs = _keyword_pairs(records)
    clusters: list[list[int]] = []
    if matrix is not None and matrix.shape[1] != 0:
        similarity = cosine_similarity(matrix)
        np.fill_diagonal(similarity, 1.0)
        candidates: list[tuple[int, float, list[list[int]]]] = []
        thresholds = list(_DEFAULT_THRESHOLDS) + [0.25]
        for threshold in thresholds:
            parent = list(range(count))
            for i, j in keyword_pairs:
                _union(parent, i, j)
            for i in range(count):
                for j in range(i + 1, count):
                    if similarity[i, j] >= threshold:
                        _union(parent, i, j)
            candidate = _clusters_from_parent(parent)
            if min_clusters <= len(candidate) <= max_clusters:
                candidates.append((len(candidate), threshold, candidate))
        if candidates:
            candidates.sort(key=lambda item: (item[0], item[1]))
            clusters = candidates[0][2]
    if not clusters:
        parent = list(range(count))
        for i, j in keyword_pairs:
            _union(parent, i, j)
        clusters = _clusters_from_parent(parent)
        if not clusters:
            clusters = [[idx] for idx in range(count)]

    clusters = _cap_clusters(clusters, max_clusters)
    clusters = _respect_minimum(clusters, min_clusters)
    return clusters


def _keyword_pairs(records: Sequence[_PainPointRecord]) -> list[tuple[int, int]]:
    mapping: dict[str, list[int]] = {}
    for idx, record in enumerate(records):
        for keyword in record.keywords:
            mapping.setdefault(keyword, []).append(idx)
    pairs: set[tuple[int, int]] = set()
    for indices in mapping.values():
        if len(indices) < 2:
            continue
        anchor = indices[0]
        for other in indices[1:]:
            pairs.add(tuple(sorted((anchor, other))))
    return sorted(pairs)


def _union(parent: list[int], a: int, b: int) -> None:
    pa = _find(parent, a)
    pb = _find(parent, b)
    if pa == pb:
        return
    if pa < pb:
        parent[pb] = pa
    else:
        parent[pa] = pb


def _find(parent: list[int], idx: int) -> int:
    while parent[idx] != idx:
        parent[idx] = parent[parent[idx]]
        idx = parent[idx]
    return idx


def _clusters_from_parent(parent: list[int]) -> list[list[int]]:
    groups: dict[int, list[int]] = {}
    for idx in range(len(parent)):
        root = _find(parent, idx)
        groups.setdefault(root, []).append(idx)
    return [sorted(indices) for indices in groups.values()]


def _cap_clusters(clusters: list[list[int]], max_clusters: int) -> list[list[int]]:
    if len(clusters) <= max_clusters:
        return clusters
    clusters = sorted(clusters, key=len, reverse=True)
    primary = clusters[:max_clusters]
    overflow = clusters[max_clusters:]
    for component in overflow:
        target = min(
            range(len(primary)),
            key=lambda idx: len(primary[idx]),
        )
        primary[target].extend(component)
    for component in primary:
        component.sort()
    return primary


def _respect_minimum(
    clusters: list[list[int]],
    min_clusters: int,
) -> list[list[int]]:
    if len(clusters) >= min_clusters:
        return clusters
    clusters = sorted(clusters, key=len, reverse=True)
    total_items = sum(len(c) for c in clusters)
    target = min(min_clusters, total_items if total_items > 0 else min_clusters)
    while len(clusters) < target:
        largest_idx = max(range(len(clusters)), key=lambda idx: len(clusters[idx]))
        largest = clusters[largest_idx]
        if len(largest) <= 1:
            break
        split_point = len(largest) // 2
        left = largest[:split_point]
        right = largest[split_point:]
        clusters[largest_idx] = left
        clusters.append(right)
    for component in clusters:
        component.sort()
    return clusters


def _summarise_cluster(
    indices: list[int],
    records: Sequence[_PainPointRecord],
    matrix: np.ndarray | None,
    vectorizer: TfidfVectorizer | None,
) -> dict[str, object]:
    items = [records[idx] for idx in indices]
    total_frequency = sum(item.frequency for item in items) or len(items)
    sentiments = [item.sentiment for item in items]
    negative_mean = float(np.mean(sentiments)) if sentiments else 0.0

    community_counter: Counter[str] = Counter()
    samples: list[str] = []
    for item in items:
        community_counter.update(item.communities)
        for sample in item.samples:
            if sample and sample not in samples:
                samples.append(sample)
            if len(samples) >= 3:
                break
        if len(samples) >= 3:
            break
    if len(samples) < 3:
        for item in items:
            if item.description not in samples:
                samples.append(item.description)
            if len(samples) >= 3:
                break

    topic = _extract_topic(indices, records, matrix, vectorizer)

    return {
        "topic": topic,
        "negative_mean": round(negative_mean, 2),
        "communities_count": len(community_counter),
        "top_communities": [name for name, _ in community_counter.most_common(3)],
        "samples": samples[:3],
        "total_frequency": total_frequency,
    }


def _extract_topic(
    indices: list[int],
    records: Sequence[_PainPointRecord],
    matrix: np.ndarray | None,
    vectorizer: TfidfVectorizer | None,
) -> str:
    if matrix is not None and vectorizer is not None:
        cluster_matrix = matrix[indices]
        if hasattr(cluster_matrix, "sum"):
            aggregated = np.asarray(cluster_matrix.sum(axis=0)).ravel()
        else:
            aggregated = np.array(cluster_matrix).sum(axis=0)
        feature_names = (
            vectorizer.get_feature_names_out()
            if hasattr(vectorizer, "get_feature_names_out")
            else vectorizer.get_feature_names()
        )
        if aggregated.size and feature_names.size:
            ranked = np.argsort(aggregated)[::-1]
            for idx in ranked:
                if idx >= feature_names.size:
                    continue
                candidate = feature_names[idx].strip()
                if candidate and candidate not in _STOPWORDS:
                    return candidate.replace("_", " ")

    primary = records[indices[0]].description
    words = [word for word in primary.split() if word and word.lower() not in _STOPWORDS]
    if words:
        return " ".join(words[:3])
    return primary[:50] if primary else "pain cluster"


from datetime import datetime, timedelta, timezone
from typing import Iterable, Optional
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


async def cluster_pain_points_from_labels(
    session: AsyncSession,
    *,
    since_days: int = 30,
    subreddits: Optional[Iterable[str]] = None,
    limit_per_source: int = 200,
) -> list[dict[str, object]]:
    """Build pain clusters directly from stable labels/entities tables.

    This aggregates both comments and posts (posts_hot) where category='pain',
    prioritises comment samples, and feeds them into the existing clustering
    routine to produce stable cluster summaries. Designed to be tolerant of
    partial data: if no records are found, returns an empty list.

    Args:
        session: Async SQLAlchemy session
        since_days: Lookback window for content selection
        subreddits: Optional subreddit filter (names like 'r/startups')
        limit_per_source: Safety cap per source type to bound input size
    """
    since_dt = datetime.now(timezone.utc) - timedelta(days=max(1, since_days))
    # Normalize subreddits to match DB variations (with and without r/ prefix)
    raw_subs = [s.lower().replace("r/", "") for s in (subreddits or []) if s]
    subs = list(set([f"r/{s}" for s in raw_subs] + raw_subs))

    # 1) Comments labelled as pain (preferred samples)
    comment_sql = text(
        """
        SELECT c.subreddit, c.body AS content, c.score, c.permalink
        FROM content_labels cl
        JOIN comments c ON c.id = cl.content_id
        WHERE cl.content_type = 'comment'
          AND cl.category IN ('pain', 'Survival')
          AND c.created_utc >= :since
          AND (:has_subs = FALSE OR lower(c.subreddit) = ANY(:subs))
        ORDER BY c.score DESC, c.created_utc DESC
        LIMIT :lim
        """
    )
    res = await session.execute(
        comment_sql,
        {"since": since_dt, "has_subs": bool(subs), "subs": subs or [""], "lim": max(50, min(2000, limit_per_source))},
    )
    comment_rows = list(res.mappings())

    # 2) Posts in hot cache labelled as pain (fallback to reach diversity)
    post_sql = text(
        """
        SELECT ph.subreddit, COALESCE(ph.title,'') || ' ' || COALESCE(ph.body,'') AS content, ph.score, NULL::text AS permalink
        FROM content_labels cl
        JOIN posts_hot ph ON ph.id = cl.content_id
        WHERE cl.content_type = 'post'
          AND cl.category IN ('pain', 'Survival')
          AND ph.created_at >= :since
          AND (:has_subs = FALSE OR lower(ph.subreddit) = ANY(:subs))
        ORDER BY ph.score DESC, ph.created_at DESC
        LIMIT :lim
        """
    )
    res2 = await session.execute(
        post_sql,
        {"since": since_dt, "has_subs": bool(subs), "subs": subs or [""], "lim": max(50, min(2000, limit_per_source))},
    )
    post_rows = list(res2.mappings())

    # Build pseudo pain-point items compatible with cluster_pain_points()
    items: list[dict[str, object]] = []
    def _mk_item(row: Mapping[str, object]) -> dict[str, object]:
        content = str(row.get("content") or "").strip()
        comm = str(row.get("subreddit") or "").strip()
        score = int(row.get("score") or 0)
        permalink = str(row.get("permalink") or "").strip()
        example = {"community": comm, "content": content}
        if permalink:
            example["permalink"] = permalink
        return {
            "description": content[:100] if content else "pain",
            "frequency": max(1, score),
            "sentiment_score": -0.2,  # unknown: default mild negative
            "severity": "medium",
            "example_posts": [example],
            "user_examples": [],
        }

    for r in comment_rows:
        items.append(_mk_item(r))
    # add a smaller portion of posts to diversify when comments are scarce
    for r in post_rows[: max(0, (len(post_rows) // 2) or 50)]:
        items.append(_mk_item(r))

    if not items:
        return []
    return cluster_pain_points(items, min_clusters=2, max_clusters=5)


from typing import Iterable, Optional
from sqlalchemy.ext.asyncio import AsyncSession


async def cluster_pain_points_auto(
    session: AsyncSession,
    *,
    since_days: int = 30,
    subreddits: Optional[Iterable[str]] = None,
    limit_per_source: int = 200,
    fallback_items: Optional[Sequence[Mapping[str, object]]] = None,
    min_clusters: int = 2,
    max_clusters: int = 5,
) -> list[dict[str, object]]:
    """
    优先用 DB 标签聚合痛点簇，不足时回落到 TF-IDF 启发式。

    - 数据足够：直接返回 DB 聚合簇
    - 数据为空/异常：使用传入的 fallback_items 经 TF-IDF 聚合
    """
    try:
        clusters = await cluster_pain_points_from_labels(
            session,
            since_days=since_days,
            subreddits=subreddits,
            limit_per_source=limit_per_source,
        )
        if clusters:
            return clusters
    except Exception:
        clusters = []

    if fallback_items:
        try:
            return cluster_pain_points(fallback_items, min_clusters=min_clusters, max_clusters=max_clusters)
        except Exception:
            return []
    return []


__all__ = ["cluster_pain_points", "cluster_pain_points_from_labels", "cluster_pain_points_auto"]
