# GitHub Actions CI/CD 配置
# 每次推送代码或创建 PR 时自动运行

name: CI/CD Pipeline

# 触发条件
on:
  push:
    branches: [ main, develop ]  # 推送到 main 或 develop 分支时触发
  pull_request:
    branches: [ main ]  # 创建 PR 到 main 分支时触发

# 定义任务
jobs:
  # 任务 1: Backend 测试
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest  # 使用 Ubuntu 系统
    timeout-minutes: 10  # 整个 job 最多运行 10 分钟

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 PostgreSQL（不依赖 Docker Hub）
      - name: Setup PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: test_user
          password: test_pass
          database: reddit_scanner_test
          port: 5432
        id: postgres

      # 3. 设置 Redis
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '7.x'
          auto-start: true

      # 4. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4.1. 缓存 Python 依赖（优化版）
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            backend/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5. 安装依赖
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      # 6. 运行数据库迁移
      - name: Run migrations
        env:
          DATABASE_URL: postgresql+asyncpg://test_user:test_pass@localhost:5432/reddit_scanner_test
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          TEST_DB_USER: test_user
          TEST_DB_PASSWORD: test_pass
          TEST_DB_NAME: reddit_scanner_test
        run: |
          cd backend
          alembic upgrade head

      # 7. 运行测试
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://test_user:test_pass@localhost:5432/reddit_scanner_test
          REDIS_URL: redis://localhost:6379/5
          CELERY_BROKER_URL: redis://localhost:6379/1
          CELERY_RESULT_BACKEND: redis://localhost:6379/2
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          TEST_DB_USER: test_user
          TEST_DB_PASSWORD: test_pass
          TEST_DB_NAME: reddit_scanner_test
        run: |
          cd backend
          # Run a focused subset to keep CI fast and stable; exclude long-running suites
          # Add explicit timeout to prevent hanging tests
          pytest -v -k "not e2e and not integration and not services and not tasks" \
            --maxfail=1 --disable-warnings \
            --timeout=60 --timeout-method=thread \
            --cov=app --cov-report=xml --cov-report=term

      # 8. 上传测试覆盖率报告
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
  
  # 任务 2: Backend 代码质量检查
  backend-quality:
    name: Backend Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            backend/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      # 类型检查
      - name: Run mypy
        run: |
          cd backend
          mypy app/ --config-file=../mypy.ini || true
        continue-on-error: true  # 允许失败，但会显示警告
      
      # 代码格式检查
      - name: Check code formatting
        run: |
          cd backend
          pip install black isort
          black --check app/
          isort --check-only app/
        continue-on-error: true  # 暂时放宽，避免阻塞 PR

  # 任务 3: Frontend 测试
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd frontend
          npm ci  # 使用 ci 而不是 install，更快更可靠
      
      - name: Run linter
        run: |
          cd frontend
          npm run lint
      
      - name: Run type check
        run: |
          cd frontend
          npm run type-check
      
      - name: Run tests
        run: |
          cd frontend
          npm test -- --run  # vitest 单次运行模式
      
      - name: Build
        run: |
          cd frontend
          npm run build
  
  # 任务 4: API 契约测试
  contract-tests:
    name: API Contract Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 缓存 Python 依赖
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            backend/.venv
          key: ${{ runner.os }}-pip-contract-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-contract-
            ${{ runner.os }}-pip-

      # 4. 安装依赖
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 检测 Breaking Changes
      - name: Check for Breaking Changes
        working-directory: backend
        run: |
          python scripts/check_breaking_changes.py

      # 6. 运行 Property-based 测试（可选，耗时较长）
      # - name: Run Schemathesis Tests
      #   working-directory: backend
      #   run: |
      #     python scripts/test_contract.py

  # 任务 5: 安全扫描（可选）
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # 允许上传 SARIF 结果到 GitHub Security

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 扫描依赖漏洞
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # 上传扫描结果到 GitHub Security
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

